kind: pipeline
type: docker
name: Build and Publish

steps:
  - name: check out
    image: drone/git
    commands:
      - git fetch --tags
      - git submodule update --init --recursive --depth=1

  - name: publish
    image: registry.oxen.rocks/lokinet-ci-android:latest
    environment:
      ANDROID_HOME: /usr/lib/android-sdk
    commands:
      - apt-get -y install ninja-build
      - update-java-alternatives -s java-1.17.0-openjdk-amd64
      - ./gradlew publish