kind: pipeline
type: docker
name: Build and Publish
trigger:
  event: [push, tag]

steps:
  - name: check out
    image: drone/git
    commands:
      - git fetch --tags
      - git submodule update --init --recursive --depth=1

  - name: publish
    image: registry.oxen.rocks/lokinet-ci-android:latest
    environment:
      ANDROID_HOME: /usr/lib/android-sdk
    commands:
      - apt-get -y update && apt-get -y install ninja-build
      - update-java-alternatives -s java-1.17.0-openjdk-amd64
      - env VERSION=`git describe --tags --dirty` ./gradlew publish

  - name: upload the artifact
    image: registry.oxen.rocks/lokinet-ci-android:latest
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
    commands:
      - apt-get -y update && apt-get -y install python3
      - ./scripts/upload-maven-artifacts.py